# Streamlit Secrets Configuration for BabyCareAI
# Copy this file and fill in your actual API keys for deployment

[llm]
# LLM Provider Configuration
LLM_PROVIDER = "openrouter"  # or "openrouter" for cloud deployment
OPENROUTER_API_KEY = "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"
OPENROUTER_MODEL = "qwen/qwen3-14b:free"  # or any other model from OpenRouter

# Example models you can use:
# - "qwen/qwen3-14b:free" (free tier)
# - "anthropic/claude-3-haiku"
# - "openai/gpt-3.5-turbo"
# - "meta-llama/llama-3-8b-instruct:free"